# General Jekyll Config
markdown: kramdown
pygments: true
#baseurl: /  
#destination: ./_site
exclude: [LICENSE, CNAME, README.md, .gitignore, drafts]
excerpt_separator: abbaab98ba8998ba898ab
#url: http://example.com
url: http://0.0.0.0:4000
#lsi: false

maruku:
    use_tex: true
    use_divs: true
    png_engine: blahtex
    png_dir: assets/images/latex/
    png_url: /assets/images/latex/

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#D52C09'
  #'#FE2B1F'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: tom-christie
    #bitbucket: philipj
    #hacker_news: swanson
    #stackexchange: 348619
    #stackoverflow: 348619
    #twitter: _swanson
    #facebook: zuck
    #tumblr: animalygifs
    #linkedin: philipjagielski
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: Tom Christie
  email: tom.christie@gmail.com
  tagline: "tagline goes here"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: 

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
